USE FasicoMang;
DELETE FROM APP.APP_TBL_Sessions
DELETE FROM APP.APP_TBL_UserOrg WHERE usoBeginDate='1393/10/10'
DELETE FROM APP.APP_TBL_Organization WHERE orgCodeInt =1000
DELETE FROM MANG.TBL_UserAccessLevelItem
DELETE FROM APP.APP_TBL_User WHERE usrNameStr=N'Œ»—'
DELETE FROM MANG.TBL_ExchangeServer
DELETE FROM MANG.TBL_SenderReceiver
DELETE FROM MANG.TBL_Region

USE FasicoNews
DELETE FROM NEWS.TBL_Action
DELETE FROM NEWS.TBL_Attachment
DELETE FROM NEWS.TBL_DashboardDeleted
DELETE FROM NEWS.TBL_UserSelectiveDashboard
DELETE FROM NEWS.TBL_SelectiveDashboard
DELETE FROM NEWS.TBL_Dashboard
DELETE FROM NEWS.TBL_NewsDetails
DELETE FROM NEWS.TBL_RelatedNews
DELETE FROM NEWS.TBL_News
DELETE FROM NEWS.TBL_Source

DELETE FROM NEWS.TBL_Evaluation
DELETE FROM NEWS.TBL_Level
DELETE FROM NEWS.TBL_NewsOrigin
DELETE FROM NEWS.TBL_Position
DELETE FROM NEWS.TBL_Priority
DELETE FROM NEWS.TBL_PriorityCC
DELETE FROM NEWS.TBL_ProtectionConsidiration
DELETE FROM NEWS.TBL_Section
DELETE FROM NEWS.TBL_Subject
DELETE FROM NEWS.TBL_SubjectType
DELETE FROM NEWS.TBL_PriorityCC
DELETE FROM NEWS.TBL_SubjectPriority
DELETE FROM NEWS.TBL_Type