
ALTER DATABASE GIS SET SINGLE_USER WITH ROLLBACK IMMEDIATE
--DROP DATABASE GIS

RESTORE DATABASE GIS
FROM  DISK = N'J:\map\GIS.bak'
WITH  FILE = 1,  
MOVE N'GIS' TO N'D:\DataDirectory\Data\GIS.mdf',
MOVE N'GIS_log' TO N'D:\DataDirectory\Log\GIS_1.ldf',
NOUNLOAD,  
STATS = 10

ALTER DATABASE GIS SET MULTI_USER
GO

